-- Seed 14 vendors with stable metadata.
-- Run after 0001_initial.sql.

insert into vendors (id, name, country, website, homepage_url, pricing_url, models_url, blog_url, is_open_source) values
  -- ───────── Overseas ─────────
  ('openai',     'OpenAI',          'US', 'https://openai.com',
                                          'https://openai.com',
                                          'https://openai.com/api/pricing',
                                          'https://platform.openai.com/docs/models',
                                          'https://openai.com/news',
                                          false),
  ('anthropic',  'Anthropic',       'US', 'https://anthropic.com',
                                          'https://anthropic.com',
                                          'https://docs.anthropic.com/en/docs/about-claude/pricing',
                                          'https://docs.anthropic.com/en/docs/about-claude/models',
                                          'https://anthropic.com/news',
                                          false),
  ('google',     'Google',          'US', 'https://ai.google',
                                          'https://ai.google.dev',
                                          'https://ai.google.dev/gemini-api/docs/pricing',
                                          'https://ai.google.dev/gemini-api/docs/models',
                                          'https://blog.google/technology/google-deepmind/',
                                          false),
  ('meta',       'Meta',            'US', 'https://ai.meta.com',
                                          'https://ai.meta.com',
                                          null,
                                          'https://www.llama.com/models',
                                          'https://ai.meta.com/blog',
                                          true),
  ('mistral',    'Mistral AI',      'FR', 'https://mistral.ai',
                                          'https://mistral.ai',
                                          'https://mistral.ai/products/la-plateforme#pricing',
                                          'https://docs.mistral.ai/getting-started/models/models_overview',
                                          'https://mistral.ai/news',
                                          true),
  ('xai',        'xAI',             'US', 'https://x.ai',
                                          'https://x.ai',
                                          'https://docs.x.ai/docs/models',
                                          'https://docs.x.ai/docs/models',
                                          'https://x.ai/blog',
                                          false),
  ('cohere',     'Cohere',          'CA', 'https://cohere.com',
                                          'https://cohere.com',
                                          'https://cohere.com/pricing',
                                          'https://docs.cohere.com/v2/docs/models',
                                          'https://cohere.com/blog',
                                          false),

  -- ───────── China ─────────
  ('deepseek',   'DeepSeek',        'CN', 'https://deepseek.com',
                                          'https://deepseek.com',
                                          'https://api-docs.deepseek.com/quick_start/pricing',
                                          'https://api-docs.deepseek.com/quick_start/pricing',
                                          'https://api-docs.deepseek.com/news/news',
                                          true),
  ('qwen',       '通义千问',          'CN', 'https://qwen.ai',
                                          'https://qwen.ai',
                                          'https://help.aliyun.com/zh/model-studio/billing-for-model-studio',
                                          'https://help.aliyun.com/zh/model-studio/models',
                                          'https://qwenlm.github.io',
                                          true),
  ('glm',        '智谱 GLM',          'CN', 'https://zhipuai.cn',
                                          'https://zhipuai.cn',
                                          'https://bigmodel.cn/pricing',
                                          'https://bigmodel.cn/dev/howuse/model',
                                          'https://bigmodel.cn/dev/news',
                                          true),
  ('doubao',     '豆包',              'CN', 'https://www.doubao.com',
                                          'https://www.volcengine.com/product/doubao',
                                          'https://www.volcengine.com/docs/82379/1099320',
                                          'https://www.volcengine.com/docs/82379/1330310',
                                          'https://www.volcengine.com/docs/82379',
                                          false),
  ('kimi',       'Kimi (Moonshot)', 'CN', 'https://kimi.moonshot.cn',
                                          'https://kimi.moonshot.cn',
                                          'https://platform.moonshot.cn/docs/pricing/chat',
                                          'https://platform.moonshot.cn/docs/intro',
                                          'https://platform.moonshot.cn/docs/changelog',
                                          false),
  ('baichuan',   '百川智能',           'CN', 'https://baichuan-ai.com',
                                          'https://baichuan-ai.com',
                                          'https://platform.baichuan-ai.com/price',
                                          'https://platform.baichuan-ai.com/docs/api',
                                          'https://baichuan-ai.com/blog',
                                          false),
  ('hunyuan',    '腾讯混元',           'CN', 'https://hunyuan.tencent.com',
                                          'https://hunyuan.tencent.com',
                                          'https://cloud.tencent.com/document/product/1729/97731',
                                          'https://cloud.tencent.com/document/product/1729/104753',
                                          'https://hunyuan.tencent.com',
                                          true)
on conflict (id) do update set
  name           = excluded.name,
  country        = excluded.country,
  website        = excluded.website,
  homepage_url   = excluded.homepage_url,
  pricing_url    = excluded.pricing_url,
  models_url     = excluded.models_url,
  blog_url       = excluded.blog_url,
  is_open_source = excluded.is_open_source;
